# Generated by Django 2.2.12 on 2020-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='default vaule', max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='default vaule', max_length=60),
        ),
    ]
