# Generated by Django 2.2.12 on 2020-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200812_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='default vaule', max_length=60)),
                ('lastName', models.CharField(default='default vaule', max_length=60)),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
